package com.sporkllm.app.ui.theme

import androidx.compose.ui.graphics.Color

// Catppuccin Mocha Colors
val CatppuccinRosewater = Color(0xFFF5E0DC)
val CatppuccinFlamingo = Color(0xFFF2CDCD)
val CatppuccinPink = Color(0xFFF5C2E7)
val CatppuccinMauve = Color(0xFFCBA6F7)
val CatppuccinRed = Color(0xFFF38BA8)
val CatppuccinMaroon = Color(0xFFEBA0AC)
val CatppuccinPeach = Color(0xFFFAB387)
val CatppuccinYellow = Color(0xFFF9E2AF)
val CatppuccinGreen = Color(0xFFA6E3A1)
val CatppuccinTeal = Color(0xFF94E2D5)
val CatppuccinSky = Color(0xFF89DCEB)
val CatppuccinSapphire = Color(0xFF74C7EC)
val CatppuccinBlue = Color(0xFF89B4FA)
val CatppuccinLavender = Color(0xFFB4BEFE)
val CatppuccinText = Color(0xFFCDD6F4)
val CatppuccinSubtext1 = Color(0xFFBAC2DE)
val CatppuccinSubtext0 = Color(0xFFA6ADC8)
val CatppuccinOverlay2 = Color(0xFF9399B2)
val CatppuccinOverlay1 = Color(0xFF7F849C)
val CatppuccinOverlay0 = Color(0xFF6C7086)
val CatppuccinSurface2 = Color(0xFF585B70)
val CatppuccinSurface1 = Color(0xFF45475A)
val CatppuccinSurface0 = Color(0xFF313244)
val CatppuccinBase = Color(0xFF1E1E2E)
val CatppuccinMantle = Color(0xFF181825)
val CatppuccinCrust = Color(0xFF11111B)

// Light Theme Colors
val LightPrimary = Color(0xFF1E88E5)
val LightSecondary = Color(0xFFE91E63)
val LightTertiary = Color(0xFFFF9800)
val LightBackground = Color(0xFFFAFAFA)
val LightSurface = Color(0xFFFFFFFF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF1C1B1F)
val LightOnSurface = Color(0xFF1C1B1F)
